// 12개의 질문을 포함한 하나의 배열!
export const questioncontent = [
  {
    number: 1,
    question: "행복한 나날을 보내던 중, 내 모든 일상이 리얼리티 쇼임을 알게 된다면?",
    answer1: "가짜 세상에서 인싸 주인공으로 살기",
    answer2: "진짜 세상에서 나만의 삶 살기",
    type: "S",
  },
  {
    number: 2,
    question: "사별한 아내와의 추억이 가득한 집. \n 최근 집값이 10배 넘게 뛰었다면?",
    answer1: "오늘부터 FLEX",
    answer2: "마지막까지 KEEP",
    type: "T",
  },
  {
    number: 3,
    question: "얼음장 같은 바다 위 여객선이 침몰했다. \n 당신과 연인. 사람은 둘, 판자는 하나",
    answer1: "교대하면서 버티자!",
    answer2: "한명이라도 살아야지!",
    type: "T",
  },
  {
    number: 4,
    question: "노트에 적히면 그 사람은 죽는다. \n 단 한 사람의 이름만 적을 수 있다면?",
    answer1: "흉악범을 적어서 정의구현",
    answer2: "나의 원수를 적어서 복수",
    type: "J",
  },
  {
    number: 5,
    question: "사고로 화성에 홀로 남겨진 당신. \n 구조도 탈출도 어렵다면?",
    answer1: "😭 아무래도 틀린 것 같다.",
    answer2: "🥔 화성에 감자라도 심어볼까?",
    type: "T",
  },
  {
    number: 6,
    question: "의문의 남자가 두 가지 알약을 내밀었다. \n 당신의 선택은?",
    answer1: "🔴 90% 확률로 1억 받기",
    answer2: "🔵 10% 확률로 1000억 받기",
    type: "J",
  },
  {
    number: 7,
    question: "외딴섬에서 시작된 생존 게임. \n 주어진 무기가 오직 프라이팬이라면?",
    answer1: "숨고, 도망가고, 총알을 막아본다",
    answer2: "만만한 상대를 찾아 무기를 빼앗는다",
    type: "E",
  },
  {
    number: 8,
    question: "이곳은 범죄가 만연한 도시 \n 당신의 운명의 남친을 고른다면?",
    answer1: "빚더미 브루스",
    answer2: "웨인재력가 조커",
    type: "J",
  },
  {
    number: 9,
    question: "필연적인 꿈을 이루기 직전인 당신, 하지만 사랑하는 사람을 희생시켜야 한다면?",
    answer1: "눈물을 머금고 내 꿈을 위해 희생시킨다",
    answer2: "그렇게 꿈을 이루면 뭐해? 당장 포기한다",
    type: "J",
  },
  {
    number: 10,
    question: "눈 떠보니 독방에 갇힌 당신! \n 그래도 정해진 시간 군만두가 나온다면?",
    answer1: "역시 바깥세상은 위험해! 자장면은 없나요?",
    answer2: "여기가 어디야? 어떻게든 나가야 돼!",
    type: "S",
  },
  {
    number: 11,
    question: " 이제는 어른이 된 나, \n 상자 속 갇혀있는 장난감을 어떡할까?",
    answer1: "🎁 소중하게 보관한다",
    answer2: "🥕마켓에 처분한다",
    type: "T",
  },
  {
    number: 12,
    question: "잠복근무를 위해 차린 통닭집이 \n 대박이 났다. 그렇다면 나는?",
    answer1: "임무를 책임지는 경찰",
    answer2: "이제부터 대박집 사장",
    type: "J",
  },
  {
    number: 13,
    question: "사교파티에 초대되었다면 당신은?",
    answer1: "눈에 들어오는 무리에 껴 대화를 나눈다",
    answer2: "사람들을 구경하며 분위기를 파악한다",
    type: "E",
  },
  {
    number: 14,
    question: "셜록홈즈가 되어 범인을 찾아내고 있을때 당신의 역할은?",
    answer1: "범인의 행동과 증거를 분석하여 수학적으로 추론",
    answer2: "범인의 심리와 동기를 파악하여 사회적인 상황과 인간관계를 고려",
    type: "E",
  },
];
